project_id = "vplwrfapmvxffnrfywqh"

[functions.fetch-google-ads-campaigns]
verify_jwt = false

[functions.fetch-google-ads-accounts]
verify_jwt = false

[functions.exchange-oauth-token]
verify_jwt = false

[functions.analyze-campaigns-openai]
verify_jwt = false

[functions.execute-optimizations]
verify_jwt = false

[functions.test-google-ads-api]
verify_jwt = false

[functions.smart-auto-optimizer]
verify_jwt = false

[functions.fixed-auto-optimizer]
verify_jwt = false

[functions.simple-optimizer]
verify_jwt = false

[functions.search-terms-report]
verify_jwt = false

[functions.keyword-optimizer]
verify_jwt = false

[functions.generate-free-audit]
verify_jwt = false

[functions.auto-generate-campaign]
verify_jwt = false
