project_id = "vplwrfapmvxffnrfywqh"

[functions.fetch-google-ads-campaigns]
verify_jwt = false

[functions.fetch-google-ads-accounts]
verify_jwt = false

[functions.exchange-oauth-token]
verify_jwt = false